require("lazynvim")
require("lsp")
require("remap")
require("colorscheme")
require("set")
require("telescope")
require("treesitter")
require("autotag")
require("surround")
require('statusline')

-- vim.cmd("language en_US")
